# Generated by Django 3.1.5 on 2021-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vlad',
            field=models.BooleanField(default=False),
        ),
    ]
