# Generated by Django 3.1.5 on 2021-04-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VladExelModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vlad_exel_file')),
                ('name', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
