# Generated by Django 3.1.5 on 2021-04-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vlad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vladexelmodels',
            old_name='file',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='vladexelmodels',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='vladexelmodels',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vladexelmodels',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
